pref("extensions.composer-open-in.custom-editor-1.label", "Notepad");
pref("extensions.composer-open-in.custom-editor-1.path", "C:\\Windows\\System32\\notepad.exe");
pref("extensions.composer-open-in.custom-editor-1.args", "");
pref("extensions.composer-open-in.custom-editor-2.label", "");
pref("extensions.composer-open-in.custom-editor-2.path", "");
pref("extensions.composer-open-in.custom-editor-2.args", "");
pref("extensions.composer-open-in.custom-editor-3.label", "");
pref("extensions.composer-open-in.custom-editor-3.path", "");
pref("extensions.composer-open-in.custom-editor-3.args", "");
